name: emote_utils
description: Emote utilities for text-based games.
version: 2.2.0
homepage: https://github.com/chrisnorman7/emote_utils

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.8
